name: Build

env:
  CI: false
  
on:
    push:
        branches:
          - master

jobs:
  release:
    name: build and release electron app
    runs-on: ${{ matrix.os }}
        
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
            
    steps:
        - name: Get version and app name
          run: |
            echo "VERSION=$(jq -r '.version' package.json)" >> $GITHUB_ENV
            echo "APP_NAME=$(jq -r '.name' package.json)" >> $GITHUB_ENV

        - name: Check out git repository
          uses: actions/checkout@v3.0.0
        
        - name: Install Node.js
          uses: actions/setup-node@v3.0.0
          with:
            node-version: "21"
            
        - name: Install Dependencies
          run: npm install
          
        - name: Build Electron App
          run: npm run build
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Build Electron Package
          run: npm run builder
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        - name: upload artifacts
          uses: actions/upload-artifact@v3.0.0
          with:
            name: ${{ matrix.os }}
            path: dist/*.exe
            
        - name: release
          uses: softprops/action-gh-release@v1
          with:
            files: "dist/*.exe"
          env:
            GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}